---
title: "puttingittogether"
author: "Evelyn Paul"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)


```
> PULL FROM GIT NOT LOCAL 

```{r}
name_data <- read_tsv("C:/Users/eviem/OneDrive/Desktop/112 Final/name.basics.tsv/data.tsv")
title_data <- read_tsv("C:/Users/eviem/OneDrive/Desktop/112 Final/title.basics.tsv/data.tsv")
ratings_by_title_code <- read_csv("C:/Users/eviem/OneDrive/Desktop/112 Final/ratings.csv")
three_composers <- read_csv("C:/Users/eviem/OneDrive/Desktop/112 Final/composer_data.csv")


```

```{r}
head(name_data)
head(ratings_by_title_code)
head(three_composers)
```

```{r}

three_composers$year <- as.numeric(as.character(three_composers$year))
title_data$startYear <- as.numeric(as.character(title_data$startYear))

danny_elfman <- subset(three_composers, cname == "Danny Elfman", select = c(tname, year, role))

# Filtering for Hans Zimmer
hans_zimmer <- subset(three_composers, cname == "Hans Zimmer", select = c(tname, year, role))

# Filtering for Daniel Pemberton
daniel_pemberton <- subset(three_composers, cname == "Daniel Pemberton", select = c(tname, year, role))

```

Elfman 

```{r}

elfman_final <- title_data %>%
  inner_join(danny_elfman, by = c("primaryTitle" = "tname", "startYear" = "year"))

elfman_final <- elfman_final %>%
  inner_join(ratings_by_title_code, by = "tconst")

head(elfman_final)

```

Pemberton 

```{r}
pemb_final <- title_data %>%
  inner_join(daniel_pemberton, by = c("primaryTitle" = "tname", "startYear" = "year"))

pemb_final <- pemb_final %>%
  inner_join(ratings_by_title_code, by = "tconst")

head(pemb_final)
```
Zimmer

```{r}

zimmer_final <- title_data %>%
  inner_join(hans_zimmer, by = c("primaryTitle" = "tname", "startYear" = "year"))

zimmer_final <- zimmer_final %>%
  inner_join(ratings_by_title_code, by = "tconst")

head(zimmer_final)

```

convenience csvs

```{r}
write.csv(elfman_final, "elfman_final.csv", row.names = FALSE)
write.csv(pemb_final, "pemb_final.csv", row.names = FALSE)
write.csv(zimmer_final, "zimmer_final.csv", row.names = FALSE)
```


